### ISSUE TITLE
Remounting goes wrong whenever folder and subvolume aren't the same

### ISSUE THREAD

**Issue by vikanezrimaya** [nyantec/igotchuu#2]
Example config:

```toml
places = ["/home", "/var/lib"]

restic_args = [
    "--repo=<REDACTED>",
    "--one-file-system", "--exclude-caches",
    "--password-file=/root/restic-password",
    "--exclude-file=<REDACTED>"
]

[[snapshots]]
source = "/home"
# Creates a snapshot with a different name (and a timestamp).
# This is useful sometimes.
[[snapshots]]
source = "/var"
```

Inspecting backup reveals following:

```console
# ls /mnt/hosts/longiflorum/latest/var/
lib

# ls /mnt/hosts/longiflorum/latest/var/lib/
cache  db  empty  guix	lib  lock  log	run  spool  tmp

# ls /mnt/hosts/longiflorum/latest/var/lib/lib
<contents of /var/lib on host>
```
